apiVersion: v1
kind: Service
metadata:
  name: Data Analytics and Feedback
  labels:
    app: Data Analytics and Feedback
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Data Analytics and Feedback