apiVersion: v1
kind: Service
metadata:
  name: Customer Service and Support
  labels:
    app: Customer Service and Support
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer Service and Support