server:
  port: 8088

---


keycloak-client:
  server-url: http://localhost:9090
  realm: master

spring:
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      default-filters:
        - TokenRelay 
      routes:
        - id: Reservation Management
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/** 
        - id: Customer Service and Support
          uri: http://localhost:8083
          predicates:
            - Path=/feedbacks/**/assistanceRequests/** 
        - id: Transportation Services Integration
          uri: http://localhost:8085
          predicates:
            - Path=/passengerLocations/**/driverNotifications/** 
        - id: Data Analytics and Feedback
          uri: http://localhost:8088
          predicates:
            - Path=/assistanceStatistics/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "gateway-path/login/oauth2/code/client-name"
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs

---

spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: Reservation Management
          uri: http://Reservation Management:8080
          predicates:
            - Path=/reservations/** 
        - id: Customer Service and Support
          uri: http://Customer Service and Support:8080
          predicates:
            - Path=/feedbacks/**/assistanceRequests/** 
        - id: Transportation Services Integration
          uri: http://Transportation Services Integration:8080
          predicates:
            - Path=/passengerLocations/**/driverNotifications/** 
        - id: Data Analytics and Feedback
          uri: http://Data Analytics and Feedback:8080
          predicates:
            - Path=/assistanceStatistics/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
