apiVersion: v1
kind: Service
metadata:
  name: Transportation Services Integration
  labels:
    app: Transportation Services Integration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Transportation Services Integration