apiVersion: v1
kind: Service
metadata:
  name: Reservation Management
  labels:
    app: Reservation Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Reservation Management